### ISSUE TITLE
Cleanup lingering netCDF Files

### ISSUE THREAD

**Issue by lukecampbell** [ioos/compliance-checker#275]
We should remove the netCDF test files from the repository since we should now dynamically generate them using ncgen. And we should describe ncgen as a project dependency in the README.

**Comment by mhidas** [comment]
I just realised `ncgen` is actually part of the standard NetCDF distribution (http://www.unidata.ucar.edu/software/netcdf/netcdf/NetCDF-Utilities.html#NetCDF-Utilities), so maybe it doesn't need to be listed separately?

**Comment by mhidas** [comment]
Just want to note a small drawback of generating netCDF test files on the fly during unit tests.

We took the same approach for the [IMOS checker plugin](https://github.com/aodn/data-services/tree/master/lib/cc_plugin_imos), and encountered a problem because our build & production environment has an older version of `ncgen`. The netCDF created can have small differences in some cases (in this case, when an `NaN` value is assigned to an attribute), which breaks one of our tests.

Since upgrading `ncgen` in that environment is not really an option at the moment, we'll either have to keep that particular netCDF test file in the repository, or disable that unit tests (not ideal).

**Comment by lukecampbell** [comment]
@ocefpaf I'm not familiar with how conda bundles netCDF, could you comment on what version of netCDF is bundled in conda? Also, do you know if `ncgen` comes with it?

**Comment by ocefpaf** [comment]
If you install `netcdf4-python` with conda from conda-forge you will get the latest libnetcdf (`netcdf 4.4.1`) with `hdf4/5` support. (Following the package feedstock is the best way to be in touch with the changes: https://github.com/conda-forge/libnetcdf-feedstock/blob/master/recipe/meta.yaml)

> Also, do you know if `ncgen` comes with it?

Yes. However, even though I know it is far more convenient to use `ncgen` and `cdl`s, I prefer to use Python code to create my netCDF files. That way I can easily integrate the creation and cleanup with pytest via fixtures. (See https://github.com/sgrid/pysgrid/blob/master/pysgrid/tests/write_nc_test_files.py for an example.)  But `ncgen`+`cdl` is fine too.

**Comment by lukecampbell** [comment]
I got really good at writing CDLs after all my work with metadata for IOOS. I also wrote a [vim plugin](https://github.com/lukecampbell/vim-folder/blob/master/syntax/cdl.vim) to do syntax highlighting for CDLs.
