### ISSUE TITLE
Performance for datasets with large number of variables

### ISSUE THREAD

**Issue by lukecampbell** [ioos/compliance-checker#445]
[test_201610.nc.zip](https://github.com/ioos/compliance-checker/files/594636/test_201610.nc.zip)

Datasets with large number of variables take considerably longer to check. We need to look at ways to optimize the performance, I believe the easiest solution is to create a timed cache for the feature reasoning functions in cfutil.

**Comment by benjwadams** [comment]
#600 took care of much of this.  Checking execution profiles revealed that much of the time was spent running `netCDF4.Dataset.get_variables_by_attributes`, so I among others opted to memoize that function since we are opening netCDF files in a read-only fashion 

Comparing the last tagged version (4.0.1) runtime against current master indicated signifcant improvements in performance for datasets residing on disk:

# 4.0.1
`python cchecker.py -t cf ~/Downloads/test_201610.nc  94.34s user 0.50s system 100% cpu 1:34.21 total`

# current master as of this writing (ad354a7eef4d82fc7d18e902b098c45300316d61)
`python cchecker.py -t cf ~/Downloads/test_201610.nc  6.99s user 0.58s system 109% cpu 6.927 total`

That seems quite a signifcant improvement in execution time, so I'm going to mark this issue as closed
