### ISSUE TITLE
The variable “aps” is referred to in a formula_terms attribute but not defined

### ISSUE THREAD

**Issue by Bobfrat** [ioos/compliance-checker#505]
Stems from this issue: https://github.com/ioos/compliance-checker/issues/501

https://drive.google.com/open?id=0B6AWgiTrQ0xFQ1J0bFVDNlpyV1k
(2) The variable “aps” is referred to in a formula_terms attribute but not defined: IOOS misses this;

**Comment by benjwadams** [comment]
This appears to be occurring because the `standard_name` value of "hybrid_sigma_is not contained in Appendix D:  http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#parametric-v-coord
I also don't see it in the standard name table:
http://cfconventions.org/Data/cf-standard-names/46/build/cf-standard-name-table.html

There is logic present to check that variables in `formula_terms` are checked, but this is only active when the `standard_name` itself is valid.

This appears to be a formula not present in Appendix D.  I also don't see the `formula` attribute in the current CF-1.7 standard.

**Comment by benjwadams** [comment]
Closing for now unless further objections raised.

**Comment by Bobfrat** [comment]
The dataset provided now fails with the following error message:
```
§4.3.2 mlev has valid formula_terms    :3:     2/ 4 : The following variable(s)
                                                      referenced in
                                                      formula_terms are not
                                                      present in the dataset
                                                      variables: aps, unknown
                                                      standard_name for
                                                      dimensionless vertical
                                                      coordinate:
                                                      hybrid_sigma_pressure
```
