### ISSUE TITLE
CF checker cell_methods error reported as warning

### ISSUE THREAD

**Issue by Bobfrat** [ioos/compliance-checker#507]
Originally part of #501

https://drive.google.com/open?id=0B6AWgiTrQ0xFX2hQMW9VTUtCQ1k
(5) Cf-checker lists one error in the cell_methods string, IOOS has this as a priority 2 message -- which is usually associated with a warning.

**Comment by lukecampbell** [comment]
My recommendation is that this is closed as no-action. I'll leave that up to the compliance-checker team but we've debated the merits of changing the priority system several times and we've always returned to the same answer that it's better than the alternatives.

In order to remain flexible for multiple standards and support the complexities of parsing datasets with little or no metadata, the priority system, in my opinion, offers the most flexible solution for guiding users to correcting the data.

**Comment by benjwadams** [comment]
I'm going to close this, mostly echoing Luke's sentiments here.  We have typically using medium priority/level 2 as recommended for CF. Although whether or not it should be considered an "error" in the compliance checker output has been discussed, the convention we have adopted for checking CF is to output "recommended" checks as level 2 checks.  For those who may be still interested in suppressing "recommended" attributes in particular checks, there likely soon be an implementation for the issue mentioned in #589 which may address some of your concerns.
