### ISSUE TITLE
Unidentifiable type messages for every variable

### ISSUE THREAD

**Issue by daltonkell** [ioos/compliance-checker#719]
When checking some datasets, there are an abundance of messages indicating that no `featureType` could be found for a set of variables, e.g.

```
§9.1 Features and feature types
* Unidentifiable feature for variable time_offset
* Unidentifiable feature for variable dt
* Unidentifiable feature for variable dtfast
* Unidentifiable feature for variable nl_tnu2
* Unidentifiable feature for variable nl_visc2
* Unidentifiable feature for variable Akt_bak
* Unidentifiable feature for variable Akv_bak
* Unidentifiable feature for variable Akk_bak
* Unidentifiable feature for variable Akp_bak
* Unidentifiable feature for variable rdrg
* Unidentifiable feature for variable Zob
* Unidentifiable feature for variable Zos
* Unidentifiable feature for variable Znudg
* Unidentifiable feature for variable M2nudg
* Unidentifiable feature for variable M3nudg
* Unidentifiable feature for variable Tnudg
* Unidentifiable feature for variable FSobc_in
* Unidentifiable feature for variable FSobc_out
...
```

Since pull request https://github.com/ioos/compliance-checker/pull/695, the following snippet seems to cause this:

https://github.com/ioos/compliance-checker/blob/380e16a4f84135605632d75e398564d6885d0de1/compliance_checker/cf/cf.py#L3773-L3787

@neumannd @benjwadams is there any indication in the spec that mandates every variable have a `featureType` attribute? If not, this should be adjusted to reflect desired behavior.

**Comment by benjwadams** [comment]
Please post file or CDL so that we can replicate the behavior.

**Comment by neumannd** [comment]
In the CF Conventions the `featureType` is only defined for _non-gridded variables_ (roughly speaking; see for details CF [9.1. Features and feature types](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#_features_and_feature_types)).

The IOOS Compliance Checker tries to guess feature types for all variables and provides different feature types for gridded data (2D grid, 3D grid; time dependence or not).

On the one hand it is a nice feature, on the other hand it causes issues as in your case or in situations with a 3D gridded and 2D gridded variable in one file. I stumpled across the same issue some month ago and wanted to raise an issue. It seems that I forgot to do it ... .

**Comment by daltonkell** [comment]
@benjwadams The behavior can be replicated using this dataset: `http://tds.eds.ioos.us/thredds/dodsC/ioos/ofs/cbofs/forecast/fields/CBOFS_Forecast_Fields_best.ncd`

**Comment by cvdwl** [comment]
I'm having several issues in the discrete sampling geometries line.  Using the attached cdl file I get the ubiquitous "* Unidentifiable feature for variable ..." issue:
 
[exH_2_timeSeries.cdl](https://github.com/ioos/compliance-checker/files/4891003/exH_2_timeSeries.cdl.txt)

Having a file with time series from multiple stations is a fairly common occurrence.  I'm still struggling to understand the CF conventions, but when the examples listed in the documentation fail CF compliance checkers, it doesn't help my understanding!

I've drawn the structure of the CDL from:

[CF conventions 1.7](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#_orthogonal_multidimensional_array_representation_of_time_series)

Note that there are a number of obvious issues with document examples (missing units and dimensions, for starters).

Note: I've tried a number of iterations of featureType and coordinates without any success; I had related issues with other files, but this is probably the simplest geometry for reproducing it.

```
metadata> ncgen cdl/exH_2_timeSeries.cdl -o tmp.nc
metadata> cchecker.py -t cf:1.7 tmp.nc 
Running Compliance Checker on the datasets from: ['tmp.nc']
Using cached standard name table v73 from /home/craig.lewis/.local/share/compliance-checker/cf-standard-name-table-test-73.xml
--------------------------------------------------------------------------------
                         IOOS Compliance Checker Report                         
                          Version 4.3.4.dev22+g58262b2                          
                     Report generated 2020-07-08T13:44:11Z                      
                                     cf:1.7                                     
http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html
--------------------------------------------------------------------------------
                               Corrective Actions                               
tmp.nc has 1 potential issue
                                     Errors                                     
--------------------------------------------------------------------------------
§9.1 Features and feature types
* Unidentifiable feature for variable humidity
```

**Comment by neumannd** [comment]
@cvdwl : Thanks for reporting the issue. I am none of the official developers but I am quite interested in the IOOS Compliance Checker.

The order of the dimensions of data variables of _timeSeries_ seems to be strange in the _timeSeries_ examples of the CF Conventions. I submitted this as a question in the CF dicussion repository: [Order of dimensions in data variables when featureType is timeSeries](https://github.com/cf-convention/discuss/issues/60). Probably, you realized it yourself and, hence, defined `float humidity(time,i)` instead of `float humidity(time,i)`. I would have done the same.

The CF IOOS Compliance Checker Plugin checks if the order of dimensions is correct. This is done in accordance with the examples provided in the CF Conventions. This is done in `cfutil.is_multi_timeseries_orthogonal(nc, variable)`:

``` python
# line 978
    dims = nc.variables[variable].dimensions
    cmatrix = coordinate_dimension_matrix(nc)

# ... some code ...

    i = cmatrix["x"][0]
    o = cmatrix["t"][0]

    if dims == (i, o):
        return True
    return False
```

If I switch `i` and `o` in the last check, everything is fine.

We should wait for the replies on my question in the CF repository.

**Comment by neumannd** [comment]
@daltonkell @benjwadams I come back to the original issue from January.

The actual issue is that the checker fails to recognize the non-geophysical variable as such. This seems to be quite a difficult task ... . Actually, I think that it cannot be solved. To reduce the list of variables shown as `Unidentifiable feature for variable ...` we could drop all variablen with no dimensions from the featureType-evaluation as follows.

We have this function call stack:

* `_find_geophysical_vars` calls `cfutil.get_geophysical_variables(ds)`
* `cfutil.get_geophysical_variables(ds)` return a list of variable with `cfutil.is_geophysical(ds, variable) == True`
* `cfutil.is_geophysical(ds, variable)` checks (amongst others):

``` python
...
    # Is it dimensionless and unitless?
    if len(ncvar.shape) == 0 and unitless:
        return False
...
```

The parameter `dtfast` (for example) has a unit but no dimensions. Therefore, it is not catched here and provided as geophysical variable. Dropping all variables here with `len(ncvar.shape) == 0` would be bad because there might be geophysical variables provided at one time and location (each with no dimension). Therefore, I would not modify `cfutil.is_geophysical` but drop all 0-dim variables in the for-loop @daltonkell posted (just line 2 modified):

```
 feature_types_found = defaultdict(list) 
 for name in [name for name in self._find_geophysical_vars(ds) if len(ds.variables[name].shape) > 0]: 
     feature = cfutil.guess_feature_type(ds, name) 
     # If we can't figure out the feature type, penalize. Originally, 
     # it was not penalized. However, this led to the issue that the 
     # message did not appear in the output of compliance checker if 
     # no other error/warning/information was printed out for section 
     # 9.1. 
     found = False 
     if feature is not None: 
         feature_types_found[feature].append(name) 
         found = True 
     all_the_same.assert_true(found, 
                              "Unidentifiable feature for variable {}" 
                              "".format(name)) 
```

**Comment by neumannd** [comment]
In general, I would consider dropping or ignoring the featureTypes that are not provided by the CF Conventions. What I mean: only check featureType of variables if a global attribute `featureType` exists and has a value listed in [Section 9.1 (Features and feature types)](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.8/cf-conventions.html#_features_and_feature_types).

**Comment by daltonkell** [comment]
Closing as #835 is merged
