### ISSUE TITLE
Dropping Python 2.7 Support

### ISSUE THREAD

**Issue by daltonkell** [ioos/compliance-checker#726]
With the [official end-of-life of Python 2.7](https://www.python.org/doc/sunset-python-2/) behind us, is it now appropriate to drop support for Python 2.7 in the automated test suites and CI?

**Comment by benjwadams** [comment]
Yes, that'd be fine to remove from Travis and elsewhere.  I believe @ocefpaf has already removed the Python 2.7 support for the AppVeyor build.

**Comment by benjwadams** [comment]
The use of Python 3 only should probably be further codified via the use of [python_requires](https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires) in `setup.py` prior to closing out this issue.

**Comment by ocefpaf** [comment]
> The use of Python 3 only should probably be further codified via the use of [python_requires](https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires) in `setup.py` prior to closing out this issue.

I'm working on a PR that removes a lot of Python 2 code and will do that too. PR soon...

**Comment by benjwadams** [comment]
@ocefpaf's previously mentioned PR, #734, likely removed most, if not all vestiges of Python 2 support.  In any event, even if we are to find some omissions in places, Python 2 will probably no longer be backwards compatible with the current codebase.  I'm going to close this issue because we've essentially ported everything over to just Python 3 at this point, and further fixup commits can be made if other behavior is found that doesn't use the preferred Python 3 idioms.
