### ISSUE TITLE
Question on handling external data tables in IOOS Compliance Checker Plugins

### ISSUE THREAD

**Issue by neumannd** [ioos/compliance-checker#744]
I am creating a Plugin for the IOOS Compliance Checker and wish to check some netCDF metadata against externally provided data tables. These externally provided data tables are update frequently. This is already the case for some existing plugins such as the CF Checker (standard names XML file) and Glider (several data tables) plugins.

I would have prefered this solution: ship the current version of the data tables with the plugin and update these tables automatically when the plugin is called at least X days after the last update. When these files are located in the plugin directory, an update is not possible due to missing write permissions (only when installed in development mode it would work):

* The CF Checker Plugin seems to ship an old version of the standard names table against which a file is checked. If a standard name table version number is explicitely provided in the global attributes, the particular version of the standard name table is downloaded into a temp folder. Alternatively, the user can provided a path of a standard name table via an environment variable.
* The Glider Plugin seems to have only the option to download tables (+ cache them) or to provide tables via an environment variable.

I am not quite happy with these approaches a thought about a modification of them for my plugin. I would like to hear your opinion before I start implementing it.

The plugin might be used on single-user workstations as well on multi-user HPC system. I though about this approach:

* First look for specific environment variable (pointing the path of the data tables); don't update the files there
* Then look for folder in the user's home; something like `${HOME}/.my_plugin/`; check if upates are available and download them; if folder does not exist: create it
* If download not possible and data-table-folder in home does not exist: use the data tables provided with the package

The use cases would be:

* On a HPC system one (the admin or similar) could configure the user's environment so that the particular environment variable is set automatically pointing to a public folder hosting the data tables. A crone job (or what-ever) could keep the data tables up to date. Thus, the user won't need to care for anything.
* On local computers the data tables would be downloaded automatically into a folder of the user's home directory if he/she did not explicitely provide the environment variable. Thus, it would work out of the box.
* Advanced users could place the data tables were they want and overwrite the environment variable.

I am not sure if the approach with the folder in the home directory works well on Windows (I was only thinking in Linux-world terms up till now). Maybe, you had a very good reason to implement the CF Checker und Glider plugins the way you did.

**Comment by daf** [comment]
You've got the right approach here - env var would have priority, then the automatic/check for updates technique.  I'd use the [XDG dirs](https://pypi.org/project/xdg/) library - probably should be stored in `XDG_DATA_HOME` somewhere.  On Linux this is typically `~/.local/share` (and you'd append `/compliance-checker` via a Path object).  Looks like this library handles Windows too, so just let it handle that for you.  Linux folks do not like it when you make your own directory off of their home.

**Comment by neumannd** [comment]
@daf: Thanks for the reply and the hint to XDG.

I asked a [similar but more general question at Stackoverflow](https://stackoverflow.com/q/60264957/4612235) and just got suggested the [appdirs](https://pypi.org/project/appdirs/) package. Both packages seem to have a similar functionality and are frequently updated ([xdg at GitHub](https://github.com/srstevenson/xdg); [appdir at GitHub](https://github.com/ActiveState/appdirs)). Do you also know appdirs and is there a good reason to prefer XDG oder appdirs?

**Comment by daf** [comment]
@neumannd appdirs looks quite good and follows the same spec; I appreciate how the docs show where the directories typically are for each of the major platforms.  You should likely use that.

**Comment by benjwadams** [comment]
Funny, was just hacking on this a little while ago on a WIP branch:

https://github.com/benjwadams/compliance-checker/tree/external_resources_cache_wip

I don't know the full history of the Compliance Checker, but in earlier versions, we only really needed to validate against the CF Standard Name list, and possibly download newer ones.  As you mentioned, there are a couple mechanisms in the glider plugin due to having multiple authority tables to validate against.  There were also some vertical datum names and other geospatial/projection related attributes introduced in CF 1.7 for which I wasn't able to easily add validation against.  For these, I had to resort to using the Proj4 SQLite database, though I'm open to suggestions for other means if they exist.

In the IOOS 1.2 spec, there are also a number of vocabularies which could be cross-referenced.  Not all of them as listed in the IOOS 1.2 implementation document would be machine readable.

Generally, I see there are about three to four issues:

1) Fetching the resources from external locations if desired
2) Creating/fetching resources from cached files if specified or if resource unreachable or user is offline.
3) Applying any transformations on the data to get into native Python data structures such as dicts, sets, and lists.  This would depend on the data format, e.g. XML would need an XPath specifying the nodes to fetch, CSV would need the column number and perhaps name if it wasn't specified in a head, and JSON would need something like `jq`'s JMESPath expressions.
4) Optionally keeping the Python data structures from steps 1, 2, and 3 in memory so that multiple invocations of the same checker don't have to refetch, or checkers that reuse external resources from existing checker resources (e.g. CF Standard Name tables) don't need to re-fetch them if say, the CF checker was already fetched.

Some of the discussion here for point 3) seems interesting.    There are obviously possible permission issues if writing to a Python module subdirectory, but some of the discussion here about writing to local directories seems like a good choice.

I was going to try to address 4) by creating a global credential store in `suite.py` or one of the non-checker modules using a singleton class with a dict which returns the key if already defined, or attempts to fetch it from a web resource, falling back to a local resource (point 2) on the filesystem if it can't be reached in 1).

**Comment by neumannd** [comment]
> I was going to try to address 4) by creating a global credential store in `suite.py` or one of the non-checker modules using a singleton class with a dict which returns the key if already defined, or attempts to fetch it from a web resource, falling back to a local resource (point 2) on the filesystem if it can't be reached in 1).

That sounds to be a reasonable approach. Are you already working on this or may I support you in implementing this?

**Comment by benjwadams** [comment]
@neumannd: I've pushed up a work-in-progress branch here: https://github.com/benjwadams/compliance-checker/tree/external_resources_cache_wip
Implementation details may change or I may rebase onto a new branch as the methods are currently stubs, but this represents an initial attempt at some of the caching mentioned in some of this discussion.

**Comment by neumannd** [comment]
@benjwadams  Thanks for pointing at it. I will have a look and see if I can contribute.
