### ISSUE TITLE
Move plugin tests to respective repositories

### ISSUE THREAD

**Issue by benjwadams** [ioos/compliance-checker#868]
There are a number of unit tests related to other compliance-checker plugins, such as the NCEI and Glider plugins which are located in the main compliance checker repo.   These should be moved to their respective repos so that any test issues can be addressed there, rather than in the core repo.

Also, there are failing tests for the glider plugin on this repo, but I am not able to reproduce them from a install using pip.

**Comment by ocefpaf** [comment]
@benjwadams I'll let you decide b/c the burden to maintain is on you. However, the plugin tests here are more on an "informative note" than a real failure for compliance-checker. It is mostly a "downstream test." The plugins do have an "upstream test" too.

With that said there is a bug in the testing, here it should be against tagged releases of the plugins, downstream it should be with development version of compliance-checker. Otherwise it does not make sense. I'll fix that ASAP.

**Comment by benjwadams** [comment]
Related: #763

**Comment by benjwadams** [comment]
OK, @ocefpaf, I see some of the rationale behind this now.  The downstream tests are failing.  The test failures look to be related to the `setup.py` entry points.  Namely, the CI setup with GitHub actions appear to not be finding them, whereas as previously mentioned, a local build using `pip` does find them.  With recent pull request merges, the downstream NCEI checks are the only remaining outstanding CI failure, so I'd like to either remove them or find out what's occurring that's causing the NCEI check suites not to be registered.
